-- Placeholder data for local/shared development only.
-- All records remain unpublished and unverified until their details, images,
-- promotions, and locations have been checked against authoritative sources.
-- Cocktail relationships remain in the frontend fixture until migration 003.

insert into public.bars (
  slug,
  name,
  short_description,
  image_url,
  image_alt,
  vibe,
  area,
  address_line,
  latitude,
  longitude,
  is_featured,
  is_published,
  is_permanently_closed,
  source_url,
  verified_at
)
values
  (
    'atlas-bar',
    'Atlas Bar',
    'A grand drinking room shaped by soaring interiors, considered hospitality, and a deep affection for classic gin cocktails.',
    'https://images.unsplash.com/photo-1640902106532-47dd3a2e833e',
    'Placeholder image of an elegant cocktail bar interior',
    'Classic',
    'Bugis',
    '18 North Bridge Road, Singapore',
    1.299200,
    103.855400,
    true,
    false,
    false,
    null,
    null
  ),
  (
    'native',
    'Native',
    'An intimate room celebrating regional ingredients through thoughtful drinks, warm service, and a distinctly Singaporean point of view.',
    'https://images.unsplash.com/photo-1578911489158-334e5cd2a051',
    'Placeholder image of an intimate cocktail bar interior',
    'Speakeasy',
    'Raffles Place',
    '52A Amoy Street, Singapore',
    1.281900,
    103.846700,
    true,
    false,
    false,
    null,
    null
  ),
  (
    'operation-dagger',
    'Operation Dagger',
    'A progressive cocktail hideaway pairing experimental techniques with an understated room made for slow, curious evenings.',
    'https://images.unsplash.com/photo-1652517816501-a884c3ad929e',
    'Placeholder image of a modern cocktail bar interior',
    'Rooftop',
    'Ann Siang',
    '7 Ann Siang Hill, Singapore',
    1.280400,
    103.845800,
    true,
    false,
    false,
    null,
    null
  ),
  (
    'analogue-initiative',
    'Analogue Initiative',
    'A forward-looking bar where inventive plant-led drinks meet a relaxed, design-conscious atmosphere.',
    'https://images.unsplash.com/photo-1646216911555-ebae58ed3dff',
    'Placeholder image of a design-conscious cocktail bar interior',
    'Casual',
    'Tanjong Pagar',
    '30 Club Street, Singapore',
    1.282100,
    103.846200,
    false,
    false,
    false,
    null,
    null
  ),
  (
    'employees-only-sg',
    'Employees Only SG',
    'A lively late-night bar balancing polished classics, generous hospitality, and a soundtrack that builds as the evening unfolds.',
    'https://images.unsplash.com/photo-1656329379773-5ff518e51ed4',
    'Placeholder image of a lively late-night cocktail bar',
    'Live Music',
    'Clarke Quay',
    '115 Amoy Street, Singapore',
    1.279400,
    103.846700,
    false,
    false,
    false,
    null,
    null
  )
on conflict (slug) do update set
  name = excluded.name,
  short_description = excluded.short_description,
  image_url = excluded.image_url,
  image_alt = excluded.image_alt,
  vibe = excluded.vibe,
  area = excluded.area,
  address_line = excluded.address_line,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  is_featured = excluded.is_featured,
  is_published = false,
  is_permanently_closed = excluded.is_permanently_closed,
  source_url = null,
  verified_at = null;
